import {
  BOXER_FRAMES,
  CAPYBARA_STATUE_IMAGE,
  CHEST_IMAGE,
  GRASS_TILE_IMAGE,
  GRASS_TILE_PATH_A_IMAGE,
  GRASS_TILE_PATH_B_IMAGE,
  GRASS_TILE_PATH_C_IMAGE,
  GRASS_TILE_PATH_D_IMAGE,
  GRASS_TILE_PATH_E_IMAGE,
  GRASS_TILE_PATH_F_IMAGE,
  GRASS_TILE_PATH_G_IMAGE,
  GRASS_TILE_PATH_H_IMAGE,
  GRASS_TILE_PATH_I_IMAGE,
  GRASS_TILE_PATH_J_IMAGE,
  QUARTERBACK_IMAGE,
  SOIL_TILE_IMAGE,
  TENNIS_FRAMES,
  TINY_HOUSE_IMAGE,
  WALL_TILE_IMAGE,
  WINDMILL_IMAGE,
  WOOD_FENCE_IMAGE,
} from './assets';
import {
  CAPYBARA_STATUE_COST,
  CAPYBARA_STATUE_PRIZE_ID,
  CHEST_COST,
  COST_BOXER,
  COST_FENCE,
  COST_GRASS,
  COST_HOUSE,
  COST_QUARTERBACK,
  COST_SOIL,
  COST_TENNIS,
  COST_WALL,
  COST_WINDMILL,
} from './costs';
import type { BuildToolDef } from './types';

export const BUILD_TOOLS: BuildToolDef[] = [
  { tool: 'grass', label: 'Grass', cost: COST_GRASS, icon: GRASS_TILE_IMAGE },
  { tool: 'grass_path_a', label: 'Path A', cost: COST_GRASS, icon: GRASS_TILE_PATH_A_IMAGE },
  { tool: 'grass_path_b', label: 'Path B', cost: COST_GRASS, icon: GRASS_TILE_PATH_B_IMAGE },
  { tool: 'grass_path_c', label: 'Path C', cost: COST_GRASS, icon: GRASS_TILE_PATH_C_IMAGE },
  { tool: 'grass_path_d', label: 'Path D', cost: COST_GRASS, icon: GRASS_TILE_PATH_D_IMAGE },
  { tool: 'grass_path_e', label: 'Path E', cost: COST_GRASS, icon: GRASS_TILE_PATH_E_IMAGE },
  { tool: 'grass_path_f', label: 'Path F', cost: COST_GRASS, icon: GRASS_TILE_PATH_F_IMAGE },
  { tool: 'grass_path_g', label: 'Path G', cost: COST_GRASS, icon: GRASS_TILE_PATH_G_IMAGE },
  { tool: 'grass_path_h', label: 'Path H', cost: COST_GRASS, icon: GRASS_TILE_PATH_H_IMAGE },
  { tool: 'grass_path_i', label: 'Path I', cost: COST_GRASS, icon: GRASS_TILE_PATH_I_IMAGE },
  { tool: 'grass_path_j', label: 'Path J', cost: COST_GRASS, icon: GRASS_TILE_PATH_J_IMAGE },
  { tool: 'fence', label: 'Fence', cost: COST_FENCE, icon: WOOD_FENCE_IMAGE },
  { tool: 'soil', label: 'Soil', cost: COST_SOIL, icon: SOIL_TILE_IMAGE },
  { tool: 'tennis', label: 'Tennis', cost: COST_TENNIS, icon: TENNIS_FRAMES[0] },
  { tool: 'boxer', label: 'Boxer', cost: COST_BOXER, icon: BOXER_FRAMES[0] },
  { tool: 'quarterback', label: 'Quarterback', cost: COST_QUARTERBACK, icon: QUARTERBACK_IMAGE },
  { tool: 'wall', label: 'Wall', cost: COST_WALL, icon: WALL_TILE_IMAGE },
  { tool: 'chest', label: 'Chest', cost: CHEST_COST, icon: CHEST_IMAGE },
  { tool: 'house', label: 'House', cost: COST_HOUSE, icon: TINY_HOUSE_IMAGE },
  { tool: 'windmill', label: 'Windmill', cost: COST_WINDMILL, icon: WINDMILL_IMAGE },
  {
    tool: 'capybara_statue',
    label: 'Capybara',
    cost: CAPYBARA_STATUE_COST,
    icon: CAPYBARA_STATUE_IMAGE,
    unlockPrizeId: CAPYBARA_STATUE_PRIZE_ID,
  },
];

export const TOOLS_PER_PAGE = 3;

