import { StyleSheet } from 'react-native';

export const hudStyles = StyleSheet.create({
  hud: { left: 0, paddingHorizontal: 14, position: 'absolute', right: 0, top: 0, zIndex: 1000 },
  hudCard: {
    backgroundColor: 'rgba(4,11,20,0.9)',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 24,
    borderWidth: 1,
    overflow: 'hidden',
    padding: 16,
  },
  hudCardAvailable: {
    borderColor: 'rgba(103,232,249,0.38)',
    shadowColor: '#22d3ee',
    shadowOpacity: 0.28,
    shadowRadius: 16,
  },
  hudCardDanger: {
    borderColor: 'rgba(248,113,113,0.55)',
    shadowColor: '#ef4444',
  },
  hudCardWarning: {
    borderColor: 'rgba(251,191,36,0.52)',
    shadowColor: '#f59e0b',
  },
  hudCardStrong: {
    borderColor: 'rgba(74,222,128,0.5)',
    shadowColor: '#22c55e',
  },
  hudReadyGradient: {
    bottom: 0,
    left: 0,
    opacity: 0.94,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  hudCardCollapsed: { paddingBottom: 12 },
  hudHeaderRow: { alignItems: 'center', columnGap: 12, flexDirection: 'row' },
  hudHeaderText: { flex: 1 },
  swarmRemainingDonut: {
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.45)',
    borderRadius: 999,
    height: 40,
    justifyContent: 'center',
    position: 'relative',
    width: 40,
  },
  swarmRemainingDonutText: {
    color: '#fef3c7',
    fontSize: 14,
    fontWeight: '900',
    left: 5,
    position: 'absolute',
    right: 5,
    textAlign: 'center',
  },
  hudToggle: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  hudToggleText: { color: '#e8f3ff', fontSize: 12, fontWeight: '800' },
  kicker: { color: '#f7a91c', fontSize: 13, fontWeight: '900', letterSpacing: 1 },
  hudActivateDefenseButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(252,211,77,0.18)',
    borderColor: 'rgba(252,211,77,0.42)',
    borderRadius: 999,
    borderWidth: 1,
    columnGap: 6,
    flexDirection: 'row',
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  hudActivateDefenseButtonDanger: {
    backgroundColor: 'rgba(248,113,113,0.16)',
    borderColor: 'rgba(248,113,113,0.48)',
  },
  hudActivateDefenseButtonWarning: {
    backgroundColor: 'rgba(251,191,36,0.16)',
    borderColor: 'rgba(251,191,36,0.48)',
  },
  hudActivateDefenseText: {
    color: '#fef3c7',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.35,
    textTransform: 'uppercase',
  },
  starBalanceRow: { alignItems: 'center', justifyContent: 'center' },
  starBalancePill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    columnGap: 10,
    flexDirection: 'row',
  },
  starBalanceIcon: { height: 16, width: 16 },
  starBalanceTextWrap: { alignItems: 'flex-start' },
  starBalanceLabel: {
    color: 'rgba(232,243,255,0.72)',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  starBalanceValue: { color: '#fcd34d', fontSize: 12, fontWeight: '900', marginTop: 2 },
  subtleText: { color: 'rgba(232,243,255,0.8)', fontSize: 13, lineHeight: 18, marginTop: 6 },
  testStarFxBtn: { alignSelf: 'flex-start', marginTop: 10 },
  statusLine: { color: '#dbeafe', fontSize: 13, fontWeight: '700', marginTop: 14 },
  swarmActionRow: { alignItems: 'stretch', columnGap: 10, flexDirection: 'row', marginTop: 10 },
  swarmExpandedInfo: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  swarmExpandedTitle: { color: '#f8fbff', fontSize: 12, fontWeight: '900' },
  swarmExpandedSubtext: { color: 'rgba(232,243,255,0.7)', fontSize: 10, fontWeight: '700', marginTop: 4 },
  swarmExpandedInfoDanger: {
    backgroundColor: 'rgba(69,10,10,0.34)',
    borderColor: 'rgba(248,113,113,0.22)',
  },
  swarmExpandedInfoWarning: {
    backgroundColor: 'rgba(67,20,7,0.34)',
    borderColor: 'rgba(251,191,36,0.22)',
  },
  swarmExpandedInfoStrong: {
    backgroundColor: 'rgba(5,46,22,0.34)',
    borderColor: 'rgba(74,222,128,0.24)',
  },
  forecastMeterRow: { alignItems: 'center', columnGap: 8, flexDirection: 'row', marginTop: 9 },
  forecastMeterTrack: {
    backgroundColor: 'rgba(15,23,42,0.74)',
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 999,
    borderWidth: 1,
    flex: 1,
    height: 9,
    overflow: 'hidden',
  },
  forecastMeterFill: {
    backgroundColor: '#22c55e',
    borderRadius: 999,
    height: '100%',
  },
  forecastMeterFillDanger: { backgroundColor: '#ef4444' },
  forecastMeterFillWarning: { backgroundColor: '#f59e0b' },
  forecastMeterFillStrong: { backgroundColor: '#86efac' },
  forecastPercent: { color: '#f8fbff', fontSize: 10, fontWeight: '900', minWidth: 74, textAlign: 'right' },
  forecastStatRow: {
    alignItems: 'center',
    columnGap: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
  },
  forecastStatPill: {
    alignItems: 'center',
    backgroundColor: 'rgba(15,23,42,0.5)',
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 999,
    borderWidth: 1,
    columnGap: 4,
    flexDirection: 'row',
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  forecastStatText: { color: 'rgba(232,243,255,0.86)', fontSize: 9, fontWeight: '800' },
  forecastSuggestionList: {
    alignItems: 'stretch',
    marginTop: 10,
  },
  forecastSuggestionPill: {
    alignItems: 'center',
    backgroundColor: 'rgba(15,23,42,0.5)',
    borderColor: 'rgba(252,211,77,0.18)',
    borderRadius: 999,
    borderWidth: 1,
    columnGap: 6,
    flexDirection: 'row',
    marginTop: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  forecastSuggestionText: {
    color: '#fef3c7',
    flex: 1,
    fontSize: 10,
    fontWeight: '800',
  },
  streakPill: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 18,
    borderWidth: 1,
    justifyContent: 'center',
    minWidth: 88,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  streakLabel: {
    color: 'rgba(232,243,255,0.72)',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  streakValue: { color: '#fcd34d', fontSize: 24, fontWeight: '900', marginTop: 4 },
  forestSpiritTracker: {
    backgroundColor: 'rgba(12,34,28,0.82)',
    borderColor: 'rgba(134,239,172,0.2)',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  forestSpiritTrackerReady: {
    backgroundColor: 'rgba(20,83,45,0.9)',
    borderColor: 'rgba(74,222,128,0.55)',
    shadowColor: '#22c55e',
    shadowOpacity: 0.28,
    shadowRadius: 14,
  },
  forestSpiritTrackerLoading: { opacity: 0.72 },
  forestSpiritHeader: {
    alignItems: 'center',
    columnGap: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 9,
  },
  forestSpiritTitleRow: { alignItems: 'center', columnGap: 6, flexDirection: 'row', flexShrink: 1 },
  forestSpiritTitle: { color: '#dcfce7', fontSize: 12, fontWeight: '900' },
  forestSpiritStatusPill: {
    alignItems: 'center',
    backgroundColor: 'rgba(15,23,42,0.62)',
    borderColor: 'rgba(134,239,172,0.24)',
    borderRadius: 999,
    borderWidth: 1,
    flexShrink: 0,
    minWidth: 136,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  forestSpiritStatusPillReady: {
    backgroundColor: 'rgba(187,247,208,0.16)',
    borderColor: 'rgba(187,247,208,0.4)',
  },
  forestSpiritStatusText: { color: '#bbf7d0', fontSize: 10, fontWeight: '900', textAlign: 'center' },
  forestSpiritStatusTextReady: { color: '#f0fdf4' },
  forestSpiritDayRow: {
    alignItems: 'center',
    columnGap: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  forestSpiritDayBubble: {
    alignItems: 'center',
    backgroundColor: 'rgba(15,23,42,0.82)',
    borderColor: 'rgba(255,255,255,0.18)',
    borderRadius: 999,
    borderWidth: 2,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  forestSpiritDayBubbleComplete: {
    backgroundColor: '#16a34a',
    borderColor: '#4ade80',
  },
  forestSpiritDayBubbleNext: {
    borderColor: 'rgba(187,247,208,0.62)',
  },
  forestSpiritDayBubbleReady: {
    backgroundColor: '#16a34a',
    borderColor: '#86efac',
  },
  forestSpiritDayText: { color: '#f8fbff', fontSize: 14, fontWeight: '900' },
  forestSpiritDayTextComplete: { color: '#f0fdf4' },
  forestSpiritDayTextReady: { color: '#f0fdf4' },
  forestSpiritRewardWrap: {
    alignItems: 'center',
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  forestSpiritRewardWrapReady: {},
  forestSpiritRewardImage: { height: 42, width: 42 },
  swarmActivateBtn: { alignItems: 'flex-start', flex: 1, paddingVertical: 12 },
  swarmActivateSubtext: { color: 'rgba(41,20,0,0.72)', fontSize: 11, fontWeight: '800', marginTop: 4 },
  exitButton: {
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  exitButtonText: { color: '#f8fafc', fontSize: 13, fontWeight: '700' },
  actionBtn: {
    alignItems: 'center',
    borderRadius: 14,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 14,
  },
  actionBtnPrimary: { backgroundColor: '#f7a91c' },
  actionBtnDisabled: { opacity: 0.6 },
  actionBtnPrimaryText: { color: '#291400', fontSize: 13, fontWeight: '900' },
  actionBtnSecondary: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
  },
  actionBtnSecondaryText: { color: '#e8f3ff', fontSize: 13, fontWeight: '700' },
});
