import { StyleSheet } from 'react-native';

export const modalStyles = StyleSheet.create({
  modalOverlay: { alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.6)', flex: 1, justifyContent: 'center' },
  modalCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(15,23,42,0.92)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 32,
    borderWidth: 1,
    elevation: 12,
    maxWidth: 400,
    padding: 24,
    paddingVertical: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.5,
    shadowRadius: 30,
    width: '85%',
  },
  modalIconRing: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 40,
    borderWidth: 2,
    height: 80,
    justifyContent: 'center',
    marginBottom: 20,
    width: 80,
  },
  modalIconText: { fontSize: 36 },
  modalTitle: { color: '#f8fbff', fontSize: 24, fontWeight: '900', marginBottom: 12, textAlign: 'center' },
  modalSubtitle: {
    color: 'rgba(232,243,255,0.7)',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    marginBottom: 24,
    paddingHorizontal: 10,
    textAlign: 'center',
  },
  modalSubtitleSmall: {
    color: 'rgba(232,243,255,0.7)',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 20,
    marginBottom: 24,
    paddingHorizontal: 10,
    textAlign: 'center',
  },
  endStateModalTitle: { fontSize: 21, marginBottom: 10 },
  endStateModalSubtitle: {
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  modalStatsRow: { columnGap: 12, flexDirection: 'row', marginBottom: 28, width: '100%' },
  modalStatPill: { alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: 16, flex: 1, padding: 12 },
  modalStatValue: { color: '#f8fbff', fontSize: 20, fontWeight: '900' },
  modalStatLabel: {
    color: 'rgba(232,243,255,0.5)',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
    textTransform: 'uppercase',
  },
  endStateModalStatValue: { fontSize: 18 },
  endStateModalButtonText: { fontSize: 15 },
  infoSectionCard: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 14,
    padding: 14,
    width: '100%',
  },
  infoSectionTitle: {
    color: '#f8fbff',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.5,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  infoSectionText: {
    color: 'rgba(232,243,255,0.82)',
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
  },
  energyInfoFactRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 5,
  },
  energyInfoFactLabel: { color: 'rgba(232,243,255,0.76)', fontSize: 13, fontWeight: '700' },
  energyInfoFactValue: { color: '#fcd34d', fontSize: 13, fontWeight: '900' },
  energyInfoBalanceRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  energyInfoBalanceLabel: { color: 'rgba(232,243,255,0.72)', fontSize: 12, fontWeight: '700' },
  energyInfoBalanceValue: { color: '#f8fbff', fontSize: 14, fontWeight: '900' },
  energyInfoBalanceValueHighlight: { color: '#67e8f9' },
  crazyCapyChargeCard: {
    backgroundColor: 'rgba(103,232,249,0.08)',
    borderColor: 'rgba(103,232,249,0.18)',
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 20,
    padding: 16,
    width: '100%',
  },
  crazyCapyChargeHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  crazyCapyChargeTitle: {
    color: '#e0f2fe',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  crazyCapyChargePercent: { color: '#67e8f9', fontSize: 18, fontWeight: '900' },
  crazyCapyChargeTrack: {
    backgroundColor: 'rgba(15,23,42,0.72)',
    borderRadius: 999,
    height: 12,
    marginTop: 12,
    overflow: 'hidden',
    width: '100%',
  },
  crazyCapyChargeFill: {
    backgroundColor: '#34d399',
    borderRadius: 999,
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
  },
  crazyCapyChargeValue: {
    color: '#f8fbff',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 12,
    textAlign: 'center',
  },
  crazyCapyChargeHint: {
    color: 'rgba(232,243,255,0.68)',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 6,
    textAlign: 'center',
  },
  modalButton: {
    alignItems: 'center',
    borderRadius: 16,
    height: 52,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    width: '100%',
  },
  modalButtonText: { color: '#0f172a', fontSize: 16, fontWeight: '900' },
  expansionBalanceCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(103,232,249,0.08)',
    borderColor: 'rgba(103,232,249,0.18)',
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 18,
    padding: 16,
    width: '100%',
  },
  expansionBalanceLabel: {
    color: 'rgba(232,243,255,0.64)',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  expansionBalanceValue: { color: '#67e8f9', fontSize: 28, fontWeight: '900', marginTop: 8 },
  expansionBalanceHint: {
    color: 'rgba(232,243,255,0.68)',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 6,
    textAlign: 'center',
  },
  expansionPickerRow: {
    alignItems: 'center',
    columnGap: 12,
    flexDirection: 'row',
    marginBottom: 18,
    width: '100%',
  },
  expansionAdjustButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 16,
    borderWidth: 1,
    height: 52,
    justifyContent: 'center',
    width: 52,
  },
  expansionAdjustButtonDisabled: { opacity: 0.35 },
  expansionAdjustButtonText: { color: '#f8fbff', fontSize: 24, fontWeight: '800' },
  expansionSummaryPill: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  expansionSummaryValue: { color: '#f8fbff', fontSize: 24, fontWeight: '900' },
  expansionSummaryLabel: { color: 'rgba(232,243,255,0.7)', fontSize: 12, fontWeight: '700', marginTop: 2 },
  expansionSummaryCost: { color: '#fcd34d', fontSize: 12, fontWeight: '800', marginTop: 6 },
  expansionWarningCard: {
    backgroundColor: 'rgba(248,113,113,0.08)',
    borderColor: 'rgba(248,113,113,0.18)',
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 20,
    padding: 14,
    width: '100%',
  },
  expansionWarningTitle: {
    color: '#fca5a5',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.8,
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  expansionWarningText: { color: 'rgba(232,243,255,0.76)', fontSize: 13, fontWeight: '600', lineHeight: 18 },
  expansionModalActions: { columnGap: 12, flexDirection: 'row', width: '100%' },
  expansionCancelButton: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    flex: 1,
  },
  expansionCancelButtonText: { color: '#f8fbff', fontSize: 16, fontWeight: '800' },
  expansionConfirmButton: { backgroundColor: '#67e8f9', flex: 1 },
  actionBtnDisabled: { opacity: 0.6 },
});
