import { StyleSheet } from 'react-native';

export const overlayStyles = StyleSheet.create({
  toolInspectCardWrap: { alignItems: 'center', left: 18, position: 'absolute', right: 18, zIndex: 980 },
  toolInspectCard: {
    backgroundColor: 'rgba(4,11,20,0.94)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 24,
    borderWidth: 1,
    elevation: 10,
    maxWidth: 520,
    paddingHorizontal: 18,
    paddingVertical: 16,
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.34,
    shadowRadius: 24,
    width: '100%',
  },
  toolInspectCloseButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(15,23,42,0.88)',
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 999,
    borderWidth: 1,
    height: 30,
    justifyContent: 'center',
    position: 'absolute',
    right: 12,
    top: 12,
    width: 30,
    zIndex: 4,
  },
  toolInspectHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 16, justifyContent: 'space-between', width: '100%' },
  toolInspectTextColumn: { flex: 1, flexShrink: 1, maxWidth: '100%', minWidth: 0 },
  toolInspectMediaWrap: { alignItems: 'flex-start', flexShrink: 0, gap: 10, width: 102 },
  toolInspectMediaCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(15,23,42,0.94)',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 24,
    borderWidth: 1,
    height: 96,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 96,
  },
  toolInspectMediaCardLocked: { backgroundColor: 'rgba(30,41,59,0.94)' },
  toolInspectMediaImage: { height: 78, width: 78 },
  toolInspectMediaSymbol: { color: '#f8fbff', fontSize: 38, fontWeight: '900', lineHeight: 42 },
  toolInspectHeadingBlock: { flex: 1, flexShrink: 1, minWidth: 0 },
  toolInspectBadge: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(245,158,11,0.14)',
    borderColor: 'rgba(245,158,11,0.3)',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  toolInspectBadgeLocked: {
    backgroundColor: 'rgba(148,163,184,0.16)',
    borderColor: 'rgba(148,163,184,0.28)',
  },
  toolInspectBadgeText: {
    color: '#fcd34d',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  toolInspectBadgeTextLocked: { color: '#e2e8f0' },
  toolInspectTitle: { color: '#f8fbff', flexShrink: 1, fontSize: 24, fontWeight: '900', textAlign: 'left' },
  toolInspectSubtitle: {
    color: 'rgba(232,243,255,0.86)',
    fontSize: 13,
    fontWeight: '700',
    flexShrink: 1,
    lineHeight: 22,
    marginTop: 10,
  },
  toolInspectSubtitleCompact: {
    fontSize: 11,
    lineHeight: 17,
    marginTop: 8,
  },
  toolInspectDetailsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 14 },
  toolInspectDetailPill: {
    backgroundColor: 'rgba(15,23,42,0.82)',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 14,
    borderWidth: 1,
    minWidth: 65,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  toolInspectDetailLabel: {
    color: 'rgba(232,243,255,0.54)',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  toolInspectDetailValue: { color: '#f8fbff', fontSize: 14, fontWeight: '800', marginTop: 4 },
  toolInspectMetaRow: { alignItems: 'flex-start', gap: 10, marginTop: 14 },
  toolInspectCostPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(30,41,59,0.92)',
    borderColor: 'rgba(252,211,77,0.24)',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  toolInspectCostPillLocked: { borderColor: 'rgba(148,163,184,0.24)' },
  toolInspectCostText: { color: '#f8fbff', fontSize: 13, fontWeight: '800' },
  toolInspectCostTextLocked: { color: '#e2e8f0' },
  toolInspectHint: { color: 'rgba(232,243,255,0.6)', fontSize: 13, fontWeight: '700', lineHeight: 18 },
  toolInspectHintCompact: { fontSize: 11, lineHeight: 16 },
  toast: {
    alignSelf: 'center',
    backgroundColor: 'rgba(6,13,22,0.88)',
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 10,
    position: 'absolute',
  },
  toastText: { color: '#f8fbff', fontSize: 13, fontWeight: '700' },
  dragGhost: {
    alignItems: 'center',
    height: 60,
    justifyContent: 'center',
    position: 'absolute',
    width: 60,
    zIndex: 9999,
  },
  dragGhostImage: { height: 60, width: 60 },
  dragGhostErase: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderColor: 'rgba(255,255,255,0.3)',
    borderRadius: 22,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  dragGhostHeal: {
    alignItems: 'center',
    backgroundColor: 'rgba(74,222,128,0.2)',
    borderColor: 'rgba(74,222,128,0.5)',
    borderRadius: 26,
    borderWidth: 2,
    height: 52,
    justifyContent: 'center',
    shadowColor: '#22c55e',
    shadowOpacity: 0.6,
    shadowRadius: 12,
    width: 52,
  },
  dragGhostHealStar: { color: '#86efac', fontSize: 12, position: 'absolute', right: 2, top: 2 },
  eraseGlyph: { color: '#fde68a', fontSize: 24, fontWeight: '900', lineHeight: 24, marginRight: 6 },
  tooltipWrap: { alignItems: 'center', position: 'absolute', width: 168 },
  tooltipCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(4,11,20,0.9)',
    borderColor: 'rgba(255,255,255,0.15)',
    borderRadius: 12,
    borderWidth: 1,
    padding: 10,
    width: '100%',
  },
  tooltipTitle: { color: '#f8fbff', fontSize: 13, fontWeight: '800', marginBottom: 4 },
  tooltipTitleRow: { alignItems: 'center', flexDirection: 'row', gap: 8, marginBottom: 4 },
  tooltipTitleInline: { marginBottom: 0 },
  tooltipStatusDot: {
    borderColor: 'rgba(255,255,255,0.4)',
    borderRadius: 5,
    borderWidth: 1,
    height: 10,
    width: 10,
  },
  tooltipStats: {
    color: 'rgba(232,243,255,0.8)',
    fontSize: 11,
    fontWeight: '600',
    marginBottom: 8,
    textAlign: 'center',
  },
  tooltipBtn: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderColor: 'rgba(255,255,255,0.2)',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  tooltipHarvestBtn: {
    backgroundColor: 'rgba(252,211,77,0.18)',
    borderColor: 'rgba(252,211,77,0.45)',
    marginTop: 2,
  },
  tooltipBtnDisabled: { opacity: 0.55 },
  tooltipBtnText: { color: '#f8fbff', fontSize: 11, fontWeight: '700', textAlign: 'center' },
  tooltipArrow: {
    backgroundColor: 'transparent',
    borderLeftColor: 'transparent',
    borderLeftWidth: 6,
    borderRightColor: 'transparent',
    borderRightWidth: 6,
    borderStyle: 'solid',
    borderTopColor: 'rgba(255,255,255,0.15)',
    borderTopWidth: 6,
    height: 0,
    marginTop: -1,
    width: 0,
  },
});
