import { StyleSheet } from 'react-native';

const TILE_WIDTH = 74;
const TILE_HEIGHT = 38;
const DIAMOND_INSET = 2;
const DIAMOND_W = TILE_WIDTH - DIAMOND_INSET * 2;
const DIAMOND_H = TILE_HEIGHT - DIAMOND_INSET * 2;
const DIAMOND_SIDE = DIAMOND_W / Math.SQRT2;
const DIAMOND_SCALE_Y = DIAMOND_H / DIAMOND_W;

export const sceneStyles = StyleSheet.create({
  container: { backgroundColor: '#081018', flex: 1 },
  sceneShell: { flex: 1 },
  sceneTranslate: { position: 'absolute' },
  sceneScale: { position: 'absolute' },
  boardShadow: {
    alignSelf: 'center',
    backgroundColor: 'rgba(1,8,18,0)',
    borderRadius: 999,
    height: 76,
    position: 'absolute',
    width: '70%',
  },
  gridLine: { backgroundColor: 'rgba(160,210,255,0.22)', height: 1, position: 'absolute' },
  cellHighlight: { alignItems: 'center', justifyContent: 'center', overflow: 'visible', position: 'absolute' },
  cellNumberWrap: {
    alignItems: 'center',
    backgroundColor: 'rgba(8,14,22,0.0)',
    borderRadius: 999,
    height: 22,
    justifyContent: 'center',
    position: 'absolute',
    width: 24,
    zIndex: 390,
  },
  cellNumberText: { color: 'rgba(8,14,22,0.0)', fontSize: 10, fontWeight: '900' },
  diamond: {
    height: DIAMOND_SIDE,
    transform: [{ scaleY: DIAMOND_SCALE_Y }, { rotate: '45deg' }],
    width: DIAMOND_SIDE,
  },
  diamondActive: { backgroundColor: 'rgba(91,185,94,0.22)' },
  diamondHover: { backgroundColor: 'rgba(251,191,36,0.38)' },
  diamondHeal: { backgroundColor: 'rgba(74,222,128,0.45)' },
  expansionGhostTile: {
    alignItems: 'center',
    backgroundColor: 'rgba(103,232,249,0.1)',
    borderColor: 'rgba(103,232,249,0.7)',
    borderRadius: 6,
    borderStyle: 'dashed',
    borderWidth: 1,
    justifyContent: 'center',
    position: 'absolute',
    transform: [{ scaleY: DIAMOND_SCALE_Y }, { rotate: '45deg' }],
  },
  expansionGhostPlusWrap: {
    alignItems: 'center',
    backgroundColor: 'rgba(8,15,23,0.8)',
    borderRadius: 14,
    height: 28,
    justifyContent: 'center',
    transform: [{ rotate: '0deg' }],
    width: 28,
  },
  placedSprite: { position: 'absolute' },
  wheatGlow: {
    backgroundColor: 'rgba(252,211,77,0.32)',
    borderRadius: 999,
    height: 34,
    position: 'absolute',
    shadowColor: '#fde68a',
    shadowOpacity: 0.9,
    shadowRadius: 12,
    width: 52,
  },
  wheatSparkle: { color: '#fff7bf', fontSize: 15, fontWeight: '900', position: 'absolute' },
  castleWrap: { alignItems: 'center', position: 'absolute' },
  castleAvatarPlatform: {
    alignSelf: 'center',
    backgroundColor: 'rgba(8,14,22,0)',
    borderRadius: 999,
    height: 10,
    position: 'absolute',
  },
  castleAvatarImage: {
    position: 'absolute',
    shadowColor: '#081018',
    shadowOpacity: 0.4,
    shadowRadius: 6,
  },
  villageAvatarWrap: { alignItems: 'center', position: 'absolute' },
  villageAvatarImage: {
    shadowColor: '#081018',
    shadowOpacity: 0.35,
    shadowRadius: 5,
  },
  villageAvatarShadow: {
    backgroundColor: 'rgba(8,14,22,0.22)',
    borderRadius: 999,
    bottom: 3,
    height: 8,
    position: 'absolute',
    width: 18,
  },
  castleBanner: {
    alignItems: 'center',
    backgroundColor: 'rgba(8,14,22,0.72)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    position: 'absolute',
  },
  castleBannerText: { color: '#fff7e8', fontSize: 11, fontWeight: '900', letterSpacing: 0.4 },
  castleHpTrackMap: {
    backgroundColor: 'rgba(8,15,23,0.8)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 999,
    borderWidth: 1,
    height: 8,
    overflow: 'hidden',
    position: 'absolute',
    width: 52,
  },
  castleHpFillMap: { backgroundColor: '#34d399', borderRadius: 999, bottom: 0, left: 0, position: 'absolute', top: 0 },
  enemyWrap: { alignItems: 'center', position: 'absolute', width: 48 },
  enemyImage: { height: 48, width: 48 },
  enemyHpTrack: {
    backgroundColor: 'rgba(8,15,23,0.72)',
    borderRadius: 999,
    height: 5,
    marginBottom: 2,
    overflow: 'hidden',
    width: 34,
  },
  enemyHpFill: { backgroundColor: '#f87171', borderRadius: 999, bottom: 0, left: 0, position: 'absolute', top: 0 },
  unitHpTrack: {
    backgroundColor: 'rgba(8,15,23,0.72)',
    borderRadius: 999,
    height: 4,
    overflow: 'hidden',
    position: 'absolute',
    width: 36,
  },
  unitHpFill: { backgroundColor: '#4ade80', borderRadius: 999, bottom: 0, left: 0, position: 'absolute', top: 0 },
  projectile: {
    backgroundColor: '#fcd34d',
    borderColor: 'rgba(255,244,188,0.9)',
    borderRadius: 999,
    borderWidth: 1,
    height: 12,
    position: 'absolute',
    shadowColor: '#fbbf24',
    shadowOpacity: 0.6,
    shadowRadius: 8,
    width: 12,
  },
  footballProjectile: {
    height: 28,
    position: 'absolute',
    shadowColor: '#f59e0b',
    shadowOpacity: 0.5,
    shadowRadius: 12,
    width: 30,
  },
  quarterbackAimLanding: {
    alignItems: 'center',
    height: TILE_HEIGHT + 4,
    justifyContent: 'center',
    position: 'absolute',
    width: TILE_WIDTH + 4,
  },
  quarterbackAimLandingDiamond: {
    backgroundColor: 'rgba(251,191,36,0.22)',
    borderColor: 'rgba(254,243,199,0.78)',
    borderStyle: 'dashed',
    borderWidth: 2,
    height: DIAMOND_SIDE,
    transform: [{ scaleY: DIAMOND_SCALE_Y }, { rotate: '45deg' }],
    width: DIAMOND_SIDE,
  },
  quarterbackAimDot: {
    backgroundColor: '#fef3c7',
    borderColor: 'rgba(146,64,14,0.75)',
    borderRadius: 999,
    borderWidth: 1,
    position: 'absolute',
    shadowColor: '#f59e0b',
    shadowOpacity: 0.56,
    shadowRadius: 6,
  },
  quarterbackAimOverlay: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 1200,
  },
  quarterbackAimTouchLayer: {
    backgroundColor: 'rgba(0,0,0,0.001)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 0,
  },
  quarterbackAimPanel: {
    alignSelf: 'center',
    backgroundColor: 'rgba(4,11,20,0.88)',
    borderColor: 'rgba(254,243,199,0.22)',
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    position: 'absolute',
    shadowColor: '#000',
    shadowOpacity: 0.28,
    shadowRadius: 14,
    width: 190,
    zIndex: 2,
  },
  quarterbackAimTitle: {
    color: '#fef3c7',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  quarterbackAimText: {
    color: 'rgba(232,243,255,0.78)',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 5,
    textAlign: 'center',
  },
  quarterbackAimPowerTrack: {
    backgroundColor: 'rgba(15,23,42,0.84)',
    borderColor: 'rgba(254,243,199,0.2)',
    borderRadius: 999,
    borderWidth: 1,
    height: 8,
    marginTop: 10,
    overflow: 'hidden',
  },
  quarterbackAimPowerFill: {
    backgroundColor: '#fbbf24',
    borderRadius: 999,
    height: '100%',
  },
  quarterbackAimCancel: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 999,
    borderWidth: 1,
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  quarterbackAimCancelText: {
    color: '#e8f3ff',
    fontSize: 11,
    fontWeight: '800',
  },
  quarterbackThrowPadWrap: {
    alignItems: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    zIndex: 1305,
  },
  quarterbackThrowPad: {
    alignItems: 'center',
    height: 118,
    justifyContent: 'center',
    overflow: 'visible',
    position: 'relative',
    width: 118,
  },
  quarterbackThrowPadBaseImage: {
    height: 118,
    position: 'absolute',
    width: 118,
  },
  quarterbackThrowPadNub: {
    alignItems: 'center',
    height: 64,
    justifyContent: 'center',
    width: 64,
  },
  quarterbackThrowPadNubImage: {
    height: 64,
    position: 'absolute',
    width: 64,
  },
  quarterbackThrowPadNubContent: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  quarterbackThrowPadText: {
    color: '#fef3c7',
    fontSize: 10,
    fontWeight: '900',
    marginTop: 1,
  },
  crazyCapyTapPulse: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    position: 'absolute',
    width: 44,
    zIndex: 605,
  },
  crazyCapyTapPulseRing: {
    borderColor: 'rgba(255,59,48,0.95)',
    borderRadius: 999,
    borderWidth: 3,
    height: 44,
    position: 'absolute',
    shadowColor: '#ff3b30',
    shadowOpacity: 0.4,
    shadowRadius: 8,
    width: 44,
  },
  crazyCapyTapPulseCore: {
    backgroundColor: 'rgba(255,59,48,0.28)',
    borderRadius: 999,
    height: 16,
    width: 16,
  },
  crazyCapyWrap: { alignItems: 'center', position: 'absolute', width: 72 },
  crazyCapyImage: { height: 72, width: 72 },
  crazyCapyPowerup: {
    alignItems: 'center',
    backgroundColor: 'rgba(4,11,20,0.72)',
    borderRadius: 14,
    borderWidth: 1,
    position: 'absolute',
    right: 16,
    shadowColor: '#000',
    shadowOpacity: 0.28,
    shadowRadius: 14,
    width: 72,
    zIndex: 980,
  },
  crazyCapyPowerupReady: {
    borderColor: 'rgba(52,211,153,0.55)',
    shadowColor: '#34d399',
    shadowOpacity: 0.32,
  },
  crazyCapyPowerupDisabled: { opacity: 0.48 },
  crazyCapyPowerupIcon: {
    borderColor: 'rgba(255,255,255,0.22)',
    borderRadius: 14,
    borderWidth: 1,
    backgroundColor: '#14251a',
    height: 60,
    overflow: 'hidden',
    position: 'relative',
    width: 72,
  },
  crazyCapyPowerupIconFill: { backgroundColor: '#34d399', bottom: 0, left: 0, position: 'absolute', right: 0 },
  crazyCapyPowerupImage: { height: 60, width: 72 },
  crazyCapyPowerupLabel: { color: '#f8fbff', fontSize: 7, fontWeight: '900', marginTop: 5, textAlign: 'center', position: 'absolute', bottom: 2, textShadowColor: "#000", textShadowRadius: 1, left: "50%", marginLeft: -25 },
  crazyCapyPowerupMeta: { color: 'rgba(232,243,255,0.78)', fontSize: 9, fontWeight: '800', marginTop: 1, textAlign: 'center' },
  debugSpawnButton: {
    backgroundColor: 'rgba(8,14,22,0.86)',
    borderColor: 'rgba(147,197,253,0.28)',
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    position: 'absolute',
    right: 16,
    shadowColor: '#000',
    shadowOpacity: 0.22,
    shadowRadius: 10,
    zIndex: 981,
  },
  debugSpawnButtonKicker: {
    color: 'rgba(191,219,254,0.82)',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  debugSpawnButtonLabel: {
    color: '#f8fafc',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 2,
  },
  waterBand: { backgroundColor: 'rgba(64,176,232,0)', height: 68, left: 0, position: 'absolute', right: 0 },
  horizonGlow: {
    alignSelf: 'center',
    backgroundColor: 'rgba(120,197,255,0)',
    borderRadius: 9,
    height: 180,
    position: 'absolute',
    top: 72,
    width: 340,
  },
});
